import { createContext } from 'react';

export const RBACCtx = createContext(null);

export const ROLES = {
  doctor: 'Doctor',
  nurse: 'Nurse',
  paramedical: 'Paramedical',
  admin: 'Admin',
};

export const ROLE_OPTIONS = Object.entries(ROLES).map(([value, label]) => ({ value, label }));

export const ROLE_PROFILES = {
  doctor: {
    initials: 'DR',
    userName: 'Dr. Priya Mehta',
    dashboardMode: 'full',
    modules: {
      dashboard: 'full',
      patients: 'edit',
      patientProfile: 'full',
      visits: 'edit',
      prescriptions: 'edit',
      labs: 'edit',
      admissions: 'full',
      clinicalNotes: 'full',
      nursingNotes: 'view',
      billing: 'view',
      staff: 'view',
      analytics: 'view',
      activity: 'view',
      settings: 'none',
    },
    patientTabs: [
      'overview',
      'visits',
      'prescriptions',
      'labs',
      'vitals',
      'documents',
      'timeline',
      'billing',
      'admissions',
    ],
    ipdTabs: 'all',
    ipdEditableTabs: 'all',
  },
  nurse: {
    initials: 'NU',
    userName: 'Nurse Asha Kumar',
    dashboardMode: 'full',
    modules: {
      dashboard: 'full',
      patients: 'view',
      patientProfile: 'nursing',
      visits: 'view',
      prescriptions: 'view',
      labs: 'view',
      admissions: 'nursing',
      clinicalNotes: 'none',
      nursingNotes: 'full',
      billing: 'none',
      staff: 'none',
      analytics: 'none',
      activity: 'none',
      settings: 'none',
    },
    patientTabs: [
      'overview',
      'visits',
      'prescriptions',
      'labs',
      'vitals',
      'documents',
      'timeline',
      'admissions',
    ],
    ipdTabs: ['overview', 'treatment', 'nursing', 'visits'],
    ipdEditableTabs: ['treatment', 'nursing', 'visits'],
  },
  paramedical: {
    initials: 'PM',
    userName: 'Ravi Kumar',
    dashboardMode: 'partial',
    modules: {
      dashboard: 'partial',
      patients: 'view',
      patientProfile: 'labs',
      visits: 'view',
      prescriptions: 'view',
      labs: 'edit',
      admissions: 'investigations',
      clinicalNotes: 'none',
      nursingNotes: 'none',
      billing: 'none',
      staff: 'none',
      analytics: 'none',
      activity: 'none',
      settings: 'none',
    },
    patientTabs: [
      'overview',
      'visits',
      'prescriptions',
      'labs',
      'documents',
      'timeline',
      'admissions',
    ],
    ipdTabs: ['overview', 'investigations'],
    ipdEditableTabs: ['investigations'],
  },
  admin: {
    initials: 'AR',
    userName: 'Dr. Reception',
    dashboardMode: 'full',
    modules: {
      dashboard: 'full',
      patients: 'full',
      patientProfile: 'full',
      visits: 'edit',
      prescriptions: 'edit',
      labs: 'edit',
      admissions: 'full',
      clinicalNotes: 'full',
      nursingNotes: 'full',
      billing: 'full',
      staff: 'full',
      analytics: 'full',
      activity: 'full',
      settings: 'full',
    },
    patientTabs: [
      'overview',
      'visits',
      'prescriptions',
      'labs',
      'vitals',
      'documents',
      'timeline',
      'billing',
      'admissions',
    ],
    ipdTabs: 'all',
    ipdEditableTabs: 'all',
  },
};

export function canAccessValue(value) {
  return value && value !== 'none';
}
